platform :ios, '13.0'

target 'URS79' do
  use_frameworks!
  
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  
  # Image handling
  pod 'SDWebImage'
  
  # Location
  pod 'CoreLocation'
  
  # Security
  pod 'CryptoSwift'
  
  # UI Components
  pod 'Lottie'
  
  # Analytics
  pod 'Firebase/Analytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end